// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Suite.Server/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.Suite.Server',
  (class Server extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
