// generated by Neptune Namespaces v4.x.x
// file: Art.Suite.Server/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Server'))
.addModules({
  Config:         require('./Config'),
  Lib:            require('./Lib'),
  StandardImport: require('./StandardImport')
});
require('./Handlers');