// generated by Neptune Namespaces v4.x.x
// file: Art.Suite.Server/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Art.Suite.Server',
  (class Server extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./Handlers/namespace');