// generated by Neptune Namespaces v4.x.x
// file: Art.Suite.Server/Handlers/namespace.js

module.exports = require('../namespace').addNamespace(
  'Handlers',
  class Handlers extends Neptune.PackageNamespace {}
);
